peeraddrs:
#  - ip: "94.156.128.153" # 70015
#    port: 8333
#  - ip: "185.148.147.47"  # 70015
#    port: 8333
#  - ip: "87.120.8.239" # 70016
#    port: 8333
#  - ip: "87.121.52.96" # 70016
#    port: 20008

  - ip: "185.148.146.24"
    port: 8333
#
#  - ip: "31.41.23.249"
#    port: 8333

network: "mainnet"
useragent: "btc-node"

dbpath: "/tmp/my.db"
pinginterval: "3600s"
pingtimeout:  "60s"
readtimeout: "5s"
writetimeout: "5s"
syncwait: "60s"
getnextpeerconnmngwait: "5s"
reconnectwait: "4s"
